linters-settings:
  govet:
    shadow: true
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 140
  goimports:
    local-prefixes: vm-chan
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  depguard:
    rules:
      main:
        files:
          - $all
        allow:
          - $gostd
          - github.com/gin-gonic/gin
          - github.com/spf13/viper
          - go.uber.org/zap
          - go.uber.org/zap/zapcore
          - github.com/prometheus/client_golang
          - github.com/swaggo
          - github.com/golang-jwt/jwt/v5
          - github.com/stretchr/testify
          - golang.org/x/crypto
          - vm-chan

linters:
  disable-all: true
  enable:
    - bodyclose
    - copyloopvar
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - mnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - mnd
        - gosec
    - text: "G101:"
      linters:
        - gosec

run:
  timeout: 5m
